Add Sound Effect to Notification
BeeeQueue/mob-timer pull request #59
Opened 2019-07-09 21:34 UTC by TamasGorgics

Based on [this](https://github.com/BeeeQueue/mob-timer/pull/19) PR.

Future plans: add mute button (or even a volume controller if possible) and other sounds to choose from. 🔨

2019-07-09 21:34 UTC, TamasGorgics commented on src/state/epics/timerEpics.ts
> +const soundEffect = new Audio('https://s3-us-west-2.amazonaws.com/s.cdpn.io/123941/Yodel_Sound_Effect.mp3')
Shall the variable name be full capital letters?

2019-07-09 21:36 UTC, TamasGorgics commented on src/utils/notifications.ts
> +  if (options && options.sound) options.sound.play().then().catch()
The `.then().catch()` part is because of the floating promise. Is there a better way of doing this? (Or shall I just ignore tslint?)

2019-07-09 21:47 UTC, BeeeQueue commented on src/state/epics/timerEpics.ts
> +const soundEffect = new Audio('https://s3-us-west-2.amazonaws.com/s.cdpn.io/123941/Yodel_Sound_Effect.mp3')
If you feel like it, there's no rule about it AFAIR.

2019-07-09 21:48 UTC, BeeeQueue commented on src/utils/notifications.ts
> +  if (options && options.sound) options.sound.play().then().catch()
We can just add a tslint-ignore here. I'll remove the rule at some point

2019-07-09 21:49 UTC, beeequeue requested changes
see comments

2019-07-09 22:04 UTC, TamasGorgics commented on src/state/epics/timerEpics.ts
> +const soundEffect = new Audio('https://s3-us-west-2.amazonaws.com/s.cdpn.io/123941/Yodel_Sound_Effect.mp3')
Having `java` background makes me feel like it ☕️

2019-07-09 22:05 UTC, TamasGorgics commented on src/utils/notifications.ts
> +  if (options && options.sound) options.sound.play().then().catch()
Sure!

2019-07-09 22:12 UTC, beeequeue approved these changes

2019-07-09 22:13 UTC, merged

2019-07-11 20:36 UTC, TarekMostafaHr commented
👏

2019-07-11 20:39 UTC, TamasGorgics commented
Sorry for hijacking your PR @TarekMostafaHr but the temptation was too strong 😄